export const THEMES = [
      // {
      //   megaqueen: {
      //     "primary": "#f82834",               
      //     "primary-content": "#fef2f2",      
      //     "secondary": "#61738d",           
      //     "secondary-content": "#f7f9fa",   
      //     "accent": "#8c4fff",            
      //     "accent-content": "#f2f0fc",      
      //     "neutral": "#010515",           
      //     "neutral-content": "#f7f9fa",     
      //     "base-100": "#f7f9fa",            
      //     "base-200": "#eef2f6",            
      //     "base-300": "#dfe5ed",            
      //     "base-content": "#0d1529",         

      //     "info": "#5ca5f5",              
      //     "info-content": "#f9f2f0",       
      //     "success": "#4dbf94",               
      //     "success-content": "#fcfdfb",     
      //     "warning": "#f5be56",             
      //     "warning-content": "#fef5e5",        
      //     "error": "#b44023",               
      //     "error-content": "#f8ece9",      

      //     "--rounded-box": "2rem",           
      //     "--rounded-btn": "2rem",        
      //     "--rounded-badge": "0.25rem",       
      //     "--animation-btn": "0.25s",         
      //     "--animation-input": "0.2s",      
      //     "--btn-focus-scale": "0.95",        
      //     "--border-btn": "1px",              
      //     "--tab-border": "1px",             
      //     "--tab-radius": "0.25rem",         
      //   }
      // },
      "light",
      "dark",
      "cupcake",
      "bumblebee",
      "emerald",
      "corporate",
      "synthwave",
      "retro",
      "cyberpunk",
      "valentine",
      "halloween",
      "garden",
      "forest",
      "aqua",
      "lofi",
      "pastel",
      "fantasy",
      "wireframe",
      "black",
      "luxury",
      "dracula",
      "cmyk",
      "autumn",
      "business",
      "acid",
      "lemonade",
      "night",
      "coffee",
      "winter",
      "dim",
      "nord",
      "sunset",
    ]